name: "Indkøbsliste"
version: "1.0.72"
slug: "indkobsliste"
description: "Nye eller opdaterende filer får nu Timestamp"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "Web-grænseflade og API"
webui: "http://[HOST]:[PORT:8000]/app/index.html"
